{"name": "test_verify_created_invoice_status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.story('Search created Invoice')\n    def test_verify_created_invoice_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and verify created invoice status'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(invoice_number)\n                time.sleep(3)\n                invoice_page.verify_invoice_in_list(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n                attach_screenshot(page, \"Invoice Verification Success\")\n            except (TimeoutError, Error, AssertionError) as e:\n                attach_screenshot(page, \"Invoice Verification Failure\")\n                print(f\"Test 'verify_created_invoice_status' failed: {e}\")\n>           raise\nE           RuntimeError: No active exception to reraise\n\ntests/test_Upload_invoice.py:76: RuntimeError"}, "steps": [{"name": "Login and verify created invoice status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"/home/laptop-obs-156/PycharmProjects/Playwright_Walkthrought/tests/test_Upload_invoice.py\", line 76, in test_verify_created_invoice_status\n    raise\n"}, "attachments": [{"name": "Input Username", "source": "076be0db-0124-49b2-9f70-094982aa9e27-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "3d03f4f0-51df-4df1-b40d-2a01a62c66d0-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "f3c8a10b-9879-4c57-ae3c-b2e0440d1c63-attachment.txt", "type": "text/plain"}, {"name": "Invoice Verification Failure", "source": "d371eda8-9064-4b2c-bda1-9804cc6b3236-attachment.png", "type": "image/png"}], "start": 1720457985399, "stop": 1720457997083}], "attachments": [{"name": "stdout", "source": "4849e543-4fba-469e-8583-6e8f73643f76-attachment.txt", "type": "text/plain"}], "start": 1720457985320, "stop": 1720457997084, "uuid": "1aa8867a-6cec-49f5-8b24-e725c0b84b7d", "historyId": "0a6e48d5408d613d4f1eeb54af380e68", "testCaseId": "0a6e48d5408d613d4f1eeb54af380e68", "fullName": "tests.test_Upload_invoice#test_verify_created_invoice_status", "labels": [{"name": "story", "value": "Search created Invoice"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "195326-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}