{"name": "test_verify_invoice_delete_status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    def test_verify_invoice_delete_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and delete invoice'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n                time.sleep(3)\n                invoice_page.delete_invoice()\n                invoice_page.verify_deletion_message(ValidationTexts.SUCCESSFUL_INVOICE_DELETE)\n                attach_screenshot(page, \"Invoice Deletion Success\")\n            except (TimeoutError, Error, AssertionError) as e:\n                attach_screenshot(page, \"Invoice Deletion Failure\")\n                print(f\"Test 'verify_invoice_delete_status' failed: {e}\")\n>           raise\nE           RuntimeError: No active exception to reraise\n\ntests/test_Upload_invoice.py:102: RuntimeError"}, "steps": [{"name": "Login and delete invoice", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"/home/laptop-obs-156/PycharmProjects/Playwright_Walkthrought/tests/test_Upload_invoice.py\", line 102, in test_verify_invoice_delete_status\n    raise\n"}, "attachments": [{"name": "Input Username", "source": "5f526d81-4854-4f0c-8e1a-2eb1f3d37fe5-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "87ec59a5-d433-4119-a5cf-03b837d01e7f-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "d9561a53-018e-4e31-8643-5cc0bf300a78-attachment.txt", "type": "text/plain"}, {"name": "Invoice Deletion Success", "source": "5f9d1837-967d-413a-810f-cdc398b76be4-attachment.png", "type": "image/png"}], "start": 1720457546365, "stop": 1720457554907}], "start": 1720457546281, "stop": 1720457554907, "uuid": "b5086c61-dff7-491b-97ac-9a37a959df2a", "historyId": "9060090de2a57dc8e145cf72124402e7", "testCaseId": "9060090de2a57dc8e145cf72124402e7", "fullName": "tests.test_Upload_invoice#test_verify_invoice_delete_status", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "192946-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}