{"name": "test_verify_invoice_delete_status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.story('Delete created Invoice')\n    def test_verify_invoice_delete_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and delete invoice'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n                time.sleep(3)\n                invoice_page.delete_invoice()\n                invoice_page.verify_deletion_message(ValidationTexts.SUCCESSFUL_INVOICE_DELETE)\n                attach_screenshot(page, \"Invoice Deletion Success\")\n            except (TimeoutError, Error, AssertionError) as e:\n                attach_screenshot(page, \"Invoice Deletion Failure\")\n                print(f\"Test 'verify_invoice_delete_status' failed: {e}\")\n>           raise\nE           RuntimeError: No active exception to reraise\n\ntests/test_Upload_invoice.py:106: RuntimeError"}, "steps": [{"name": "Login and delete invoice", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"/home/laptop-obs-156/PycharmProjects/Playwright_Walkthrought/tests/test_Upload_invoice.py\", line 106, in test_verify_invoice_delete_status\n    raise\n"}, "attachments": [{"name": "Input Username", "source": "e8a56028-f9d7-4f72-8f08-e2d7266fb0bf-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "134a6cef-68bf-4dc0-891a-887fa10e6c5b-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "8a4b2bb4-bd60-4f77-b6b9-8a411a3aa542-attachment.txt", "type": "text/plain"}, {"name": "Invoice Deletion Failure", "source": "fe0d2c6e-f7a1-4cb1-8c05-70cc59117a79-attachment.png", "type": "image/png"}], "start": 1720458003565, "stop": 1720458010469}], "attachments": [{"name": "stdout", "source": "68eb2a59-633d-41ce-9919-17214a27cce9-attachment.txt", "type": "text/plain"}], "start": 1720458003447, "stop": 1720458010469, "uuid": "cf946bff-a8fc-44c6-9e05-95872ee1bff5", "historyId": "9060090de2a57dc8e145cf72124402e7", "testCaseId": "9060090de2a57dc8e145cf72124402e7", "fullName": "tests.test_Upload_invoice#test_verify_invoice_delete_status", "labels": [{"name": "story", "value": "Delete created Invoice"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "195326-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}