{"name": "test_verify_created_invoice_status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    def test_verify_created_invoice_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and verify created invoice status'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(invoice_number)\n                time.sleep(3)\n                invoice_page.verify_invoice_in_list(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n                attach_screenshot(page, \"Invoice Verification Success\")\n            except (TimeoutError, Error, AssertionError) as e:\n                attach_screenshot(page, \"Invoice Verification Failure\")\n                print(f\"Test 'verify_created_invoice_status' failed: {e}\")\n>           raise\nE           RuntimeError: No active exception to reraise\n\ntests/test_Upload_invoice.py:73: RuntimeError"}, "steps": [{"name": "Login and verify created invoice status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"/home/laptop-obs-156/PycharmProjects/Playwright_Walkthrought/tests/test_Upload_invoice.py\", line 73, in test_verify_created_invoice_status\n    raise\n"}, "attachments": [{"name": "Input Username", "source": "5617c2ba-2d4e-4551-ae95-2fe1d8515478-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "339dbcb1-f3b3-44d1-9f61-c32dc589b5eb-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "1f18703b-5f29-459b-9aaa-320cc5e2251c-attachment.txt", "type": "text/plain"}, {"name": "Invoice Verification Success", "source": "941d9a00-e627-4684-a4ad-0420d3ac8e88-attachment.png", "type": "image/png"}], "start": 1720457533253, "stop": 1720457540386}], "start": 1720457533180, "stop": 1720457540386, "uuid": "1ddc5e6c-7ea6-4233-b8e4-8fe8302d3e7c", "historyId": "0a6e48d5408d613d4f1eeb54af380e68", "testCaseId": "0a6e48d5408d613d4f1eeb54af380e68", "fullName": "tests.test_Upload_invoice#test_verify_created_invoice_status", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "192946-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}