{"name": "test_add_invoice", "status": "failed", "statusDetails": {"message": "Failed: Failed to add invoice: Locator expected to have text 'Invoice Uploaded successfully'\nActual value: <element(s) not found> \nCall log:\nLocatorAssertions.to_have_text with timeout 5000ms\n  - waiting for locator(\"//span[@class='alert-message']\")", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.story('Add Invoice')\n    def test_add_invoice(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_data = {\n            'invoice_number': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1),\n            'invoice_amount': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 2),\n            'attachment': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 3)\n        }\n    \n        with allure.step('Login and upload invoice'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_data['invoice_number']}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Amount: {invoice_data['invoice_amount']}\", name=\"Invoice Amount\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Attachment: {invoice_data['attachment']}\", name=\"Attachment\",\n                          attachment_type=allure.attachment_type.TEXT)\n        try:\n            invoice_page.login(credentials['username'], credentials['password'])\n            invoice_page.upload_invoice(invoice_data['invoice_number'], invoice_data['invoice_amount'],\n                                        invoice_data['attachment'])\n>           invoice_page.verify_confirmation_message(ValidationTexts.SUCCESSFUL_INVOICE_UPLOAD)\n\ntests/test_Upload_invoice.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.UploadInvoicePage.UploadInvoicePage object at 0x7f4352d946a0>, expected_message = 'Invoice Uploaded successfully'\n\n    def verify_confirmation_message(self, expected_message: str) -> None:\n        try:\n>           expect(self.get_element('confirmation_message')).to_have_text(expected_message)\nE           AssertionError: Locator expected to have text 'Invoice Uploaded successfully'\nE           Actual value: <element(s) not found> \nE           Call log:\nE           LocatorAssertions.to_have_text with timeout 5000ms\nE             - waiting for locator(\"//span[@class='alert-message']\")\n\npages/UploadInvoicePage.py:85: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nsetup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.story('Add Invoice')\n    def test_add_invoice(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_data = {\n            'invoice_number': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1),\n            'invoice_amount': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 2),\n            'attachment': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 3)\n        }\n    \n        with allure.step('Login and upload invoice'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_data['invoice_number']}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Amount: {invoice_data['invoice_amount']}\", name=\"Invoice Amount\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Attachment: {invoice_data['attachment']}\", name=\"Attachment\",\n                          attachment_type=allure.attachment_type.TEXT)\n        try:\n            invoice_page.login(credentials['username'], credentials['password'])\n            invoice_page.upload_invoice(invoice_data['invoice_number'], invoice_data['invoice_amount'],\n                                        invoice_data['attachment'])\n            invoice_page.verify_confirmation_message(ValidationTexts.SUCCESSFUL_INVOICE_UPLOAD)\n            attach_screenshot(page, \"Invoice Upload Success\")\n        except (TimeoutError, Error, AssertionError) as e:\n            attach_screenshot(page, \"Invoice Upload Failure\")\n            print(f\"Test 'add_invoice' failed: {e}\")\n>           pytest.fail(f\"Failed to add invoice: {str(e)}\")\nE           Failed: Failed to add invoice: Locator expected to have text 'Invoice Uploaded successfully'\nE           Actual value: <element(s) not found> \nE           Call log:\nE           LocatorAssertions.to_have_text with timeout 5000ms\nE             - waiting for locator(\"//span[@class='alert-message']\")\n\ntests/test_Upload_invoice.py:49: Failed"}, "steps": [{"name": "Login and upload invoice", "status": "passed", "attachments": [{"name": "Input Username", "source": "75b73efc-c0b9-4059-a85c-d321b903659c-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "d26613a4-bbab-4e9f-be95-45270d80d932-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "dbd0c003-6807-49e2-b9f8-8535367154b9-attachment.txt", "type": "text/plain"}, {"name": "Invoice Amount", "source": "e2805762-cd16-4e06-b8c8-4d68ec5aaa9d-attachment.txt", "type": "text/plain"}, {"name": "Attachment", "source": "d0db1c96-c1bf-4e0d-856f-62862c5cce3a-attachment.txt", "type": "text/plain"}], "start": 1720515011394, "stop": 1720515011395}], "attachments": [{"name": "Invoice Upload Failure", "source": "0eb3b106-5745-41e0-ab63-2d6c48a7262b-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "5cddad33-a47e-4262-a1b2-2b9d1d8b3554-attachment.txt", "type": "text/plain"}], "start": 1720515011288, "stop": 1720515031613, "uuid": "48ccc2a1-d3da-4bc0-b3d1-d0576d812d23", "historyId": "1c19e96ac1fa7f5df8070d5766cac19e", "testCaseId": "1c19e96ac1fa7f5df8070d5766cac19e", "fullName": "tests.test_Upload_invoice#test_add_invoice", "labels": [{"name": "story", "value": "Add Invoice"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "59267-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}